#!/bin/bash
# .openshift/action_hooks/build

# Change home directory (npm puts a lot of cache and tmp directories here)
HOME=$OPENSHIFT_REPO_DIR
cd $OPENSHIFT_REPO_DIR

if [ "$OPENSHIFT_GEAR_UUID"=="$OPENSHIFT_APP_UUID" ]; then
  # Main gear - cache node_modules for quicker pushes
  mkdir -p "$OPENSHIFT_DATA_DIR"node_modules
  ln -s "$OPENSHIFT_DATA_DIR"node_modules node_modules
fi

npm install --loglevel error